# 应用服务配置
server:
  port: 6276

# 日志
logger:
  level: 0 # 日志记录的等级 0:silent<1:info<2:warn<3:error

# security 安全
security:
  csrf:
    refererWhiteList:
      - "localhost:6269"
      - "127.0.0.1:6269"
      - "localhost:6265"
      - "127.0.0.1:6265"
      - "127.0.0.1:6275"
      - "127.0.0.1:6276"
      - "192.168.1.3"

# GORM 数据源
gorm:
  dataSource:
    default:
      type: "mysql"
      host: "192.168.1.4"
      port: 3306
      username: "root"
      password: "root@1234"
      database: "mask_api"
      logging: true

# Redis 缓存数据
redis:
  dataSource:
    default:
      port: 6379 # Redis port
      host: "192.168.1.4"
      password: "redis@1234"
      db: 0 # Redis db_num
