# 应用服务配置
server:
  port: 6276

# security 安全
security:
  csrf:
    refererWhiteList:
      - "localhost:6269"
      - "127.0.0.1:6269"
      - "localhost:6265"
      - "127.0.0.1:6265"
      - "127.0.0.1:6275"
      - "127.0.0.1:6276"
      - "192.168.56.101"

# GORM 数据源
gorm:
  dataSource:
    default:
      type: "mysql"
      host: "192.168.56.102"
      port: 3306
      username: "root"
      password: "root@1234"
      database: "mask_api"
      logging: true

# Redis 缓存数据
redis:
  client:
    port: 6379
    host: "192.168.56.102"
    password: "redis@1234"
    db: 0
