# 应用服务配置
server:
  port: 6275
  proxy: true

# security 安全
security:
  csrf:
    # 允许调用的域名地址的，例如：http://<Referer地址>/mask-api
    refererWhiteList:
      - "127.0.0.1:6275"
      - "<Referer地址>"

# GORM 数据源
gorm:
  dataSource:
    default:
      type: "mysql"
      host: "<mysql地址>"
      port: 3306
      username: "<用户名>"
      password: "<密码>"
      database: "<数据库>"

# Redis 缓存数据
redis:
  dataSource:
    default:
      port: 6379 # Redis port
      host: "<redis地址>"
      password: "<密码>"
      db: 0 # Redis db_num
