## 第一阶段 ====> 打包编译输出可执行文件
FROM golang:alpine AS builder

## 禁用cgo  
ENV CGO_ENABLED 0

## 设置构建目标
ENV GOOS linux

## 依赖下载代理
ENV GOPROXY https://goproxy.cn,direct

## 工作目录存放程序源码
WORKDIR /home/mask_api_gin

## 复制实际需要的文件到工作目录
COPY ./assets ./assets
COPY ./src ./src
COPY ./go.sum ./
COPY ./go.mod ./
COPY ./main.go ./

## 安装程序依赖，需要编译
RUN go mod download

## 进行源码编译，生产文件 app
RUN go build -ldflags="-s -w" -o app

## 第二阶段 ====> 构建可执行文件镜像
FROM alpine

## 工作目录存放程序可执行程序
WORKDIR /home/mask_api_gin

## 安装时区工具
RUN apk add --no-cache tzdata

## 设置本地区时
ENV TZ="Asia/Shanghai"

## 将第一阶段必要文件复制到
COPY --from=builder /home/mask_api_gin/assets /home/mask_api_gin/assets
COPY --from=builder /home/mask_api_gin/src/config /home/mask_api_gin/config
COPY --from=builder /home/mask_api_gin/go.mod /home/mask_api_gin/go.mod
COPY --from=builder /home/mask_api_gin/app /home/mask_api_gin/app

## 暴露端口要与程序端口一致
EXPOSE 6275

## 程序启动命令
CMD ["./app", "--env", "prod"]
